/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author ruqayahalmubiareek
 */
public class addNewProduct extends javax.swing.JFrame {

    
    
        Connection con=null;
        Statement st=null;
        ResultSet rs=null;
        String s;
        
        public void Referesh() {  
    pNumTF.setText("");  
    pNameTF.setText("");  
    pPriceTF.setText("");  
}  
        
    
    /**
     * Creates new form NewJFrame2
     */
    public addNewProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DessertRB = new javax.swing.JRadioButton();
        BreadRB = new javax.swing.JRadioButton();
        DrinkRB = new javax.swing.JRadioButton();
        PicButton = new javax.swing.JButton();
        pNumTF = new javax.swing.JTextField();
        pPriceTF = new javax.swing.JTextField();
        pNameTF = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        buttonGroup.add(BreadRB);
        buttonGroup.add(DessertRB);
        buttonGroup.add(DrinkRB);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Menu :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 60, -1));

        DessertRB.setBackground(new java.awt.Color(255, 255, 204));
        DessertRB.setFont(new java.awt.Font("Stencil", 0, 13)); // NOI18N
        DessertRB.setText("Dessert");
        jPanel1.add(DessertRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        BreadRB.setBackground(new java.awt.Color(255, 255, 204));
        BreadRB.setFont(new java.awt.Font("Stencil", 0, 13)); // NOI18N
        BreadRB.setText("Bread");
        BreadRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreadRBActionPerformed(evt);
            }
        });
        jPanel1.add(BreadRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 80, -1));

        DrinkRB.setBackground(new java.awt.Color(255, 255, 204));
        DrinkRB.setFont(new java.awt.Font("Stencil", 0, 13)); // NOI18N
        DrinkRB.setText("Drinks");
        DrinkRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinkRBActionPerformed(evt);
            }
        });
        jPanel1.add(DrinkRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        PicButton.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        PicButton.setText("Add Picture");
        PicButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PicButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PicButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 230, 30));

        pNumTF.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        pNumTF.setForeground(new java.awt.Color(153, 153, 153));
        pNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNumTFActionPerformed(evt);
            }
        });
        jPanel1.add(pNumTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 230, 30));

        pPriceTF.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        pPriceTF.setForeground(new java.awt.Color(153, 153, 153));
        pPriceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pPriceTFActionPerformed(evt);
            }
        });
        jPanel1.add(pPriceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 230, 30));

        pNameTF.setFont(new java.awt.Font("Malayalam MN", 3, 18)); // NOI18N
        pNameTF.setForeground(new java.awt.Color(153, 153, 153));
        pNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(pNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 230, 30));

        BackButton.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        BackButton.setText("Back ");
        BackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 140, 30));

        AddButton.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        AddButton.setText("Add Product");
        AddButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 150, 30));

        jLabel5.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Product Price:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Product Number:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/DarkGrayBg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 420));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Castellar", 0, 30)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Add Product");
        jPanel2.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 290, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    private void BreadRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreadRBActionPerformed
        
    }//GEN-LAST:event_BreadRBActionPerformed

    private void PicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PicButtonActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "tif"));
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
        File selectedFile = fileChooser.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
        s = path;
        
            
            
        }
        
        
    }//GEN-LAST:event_PicButtonActionPerformed

    private void pPriceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pPriceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pPriceTFActionPerformed

    private void pNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNumTFActionPerformed

    private void pNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNameTFActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new adminPage().setVisible(true); 
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        String pNumber = pNumTF.getText();
        String pName = pNameTF.getText();
        String pPrice = pPriceTF.getText();

        try {
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bakery","root","dalia");
            PreparedStatement ps = con.prepareStatement("Insert into products values(?,?,?,?,?)");

              InputStream is = new FileInputStream(new File(s));
               ps.setInt(1, Integer.parseInt(pNumTF.getText()));
               ps.setString(2, pNameTF.getText());
               String type="";
               
               if(BreadRB.isSelected())
                   type="Bread";
               if(DessertRB.isSelected())
                   type="Dessert";
               if(DrinkRB.isSelected())
                   type="Drinks";
               ps.setString(3, type);
               ps.setDouble(4, Double.parseDouble(pPriceTF.getText()));
               ps.setBlob(5,is);
               
               int v = ps.executeUpdate();
              
               if(v==1){
                   JOptionPane.showMessageDialog(this,"Product Added Successfully ..");
               Referesh();
               }
               
          
        } catch (SQLException ex) {
            if (ex instanceof SQLIntegrityConstraintViolationException) {
        JOptionPane.showMessageDialog(this,"Product Already Exist ..");
        } else {
        Logger.getLogger(addNewProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addNewProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex){
        JOptionPane.showMessageDialog(null,"Information not filled, you can't Add the Product !","Data Missing",JOptionPane.INFORMATION_MESSAGE);
                } 
    
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DrinkRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinkRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinkRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton BreadRB;
    private javax.swing.JRadioButton DessertRB;
    private javax.swing.JRadioButton DrinkRB;
    private javax.swing.JButton PicButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField pNameTF;
    private javax.swing.JTextField pNumTF;
    private javax.swing.JTextField pPriceTF;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
