/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author ruqayahalmubiareek
 */
public class adminPage extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form NewJFrame
     */
    public adminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    adminPage(String admin_Page) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        AddLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        DeleteLabel = new javax.swing.JLabel();
        CheckButton = new javax.swing.JButton();
        CheckLabel = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        UpdateLabel = new javax.swing.JLabel();
        ViewCustomerButton = new javax.swing.JButton();
        ViewLabel = new javax.swing.JLabel();
        ExitButton1 = new javax.swing.JButton();
        Frame_Image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AdminLabel = new javax.swing.JLabel();
        viewButton = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(745, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Add.png"))); // NOI18N
        AddButton.setPreferredSize(new java.awt.Dimension(200, 130));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 100, 100));

        AddLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AddLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddLabel.setText("Add New Product");
        jPanel1.add(AddLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 120, 20));

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Delete.png"))); // NOI18N
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, 100));

        DeleteLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DeleteLabel.setForeground(new java.awt.Color(255, 255, 255));
        DeleteLabel.setText("Delete Product");
        jPanel1.add(DeleteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        CheckButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Order.png"))); // NOI18N
        CheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CheckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 100));

        CheckLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CheckLabel.setForeground(new java.awt.Color(255, 255, 255));
        CheckLabel.setText("Ckeck All Order");
        jPanel1.add(CheckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Update.png"))); // NOI18N
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 100, 100));

        UpdateLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpdateLabel.setForeground(new java.awt.Color(255, 255, 255));
        UpdateLabel.setText("Update Price");
        jPanel1.add(UpdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 100, -1));

        ViewCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Customer.png"))); // NOI18N
        ViewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ViewCustomerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 100, 100));

        ViewLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ViewLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewLabel.setText("View Customers");
        jPanel1.add(ViewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, -1, -1));

        ExitButton1.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        ExitButton1.setText("Log Out");
        ExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 120, 30));

        Frame_Image.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        Frame_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Background.png"))); // NOI18N
        Frame_Image.setText("jLabel1");
        Frame_Image.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(Frame_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 90, 750, 480));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 740, 20));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        AdminLabel.setFont(new java.awt.Font("Castellar", 0, 26)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setText("Admin");

        viewButton.setBackground(new java.awt.Color(0, 0, 0));
        viewButton.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        viewButton.setForeground(new java.awt.Color(255, 255, 255));
        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/customerWH.png"))); // NOI18N
        viewButton.setBorderPainted(false);
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(AdminLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdminLabel))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        new addNewProduct().setVisible(true); 
        dispose();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        new deleteProduct().setVisible(true); 
        dispose();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed

        new adminPersonal().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_viewButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        new updateProductPrice().setVisible(true); 
        dispose();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void CheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckButtonActionPerformed
        new orders().setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckButtonActionPerformed

    private void ViewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerButtonActionPerformed
        new CustomerInfo().setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewCustomerButtonActionPerformed

    private void ExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton1ActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel AddLabel;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JButton CheckButton;
    private javax.swing.JLabel CheckLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel DeleteLabel;
    private javax.swing.JButton ExitButton1;
    private javax.swing.JLabel Frame_Image;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel UpdateLabel;
    private javax.swing.JButton ViewCustomerButton;
    private javax.swing.JLabel ViewLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mousePressed(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
